on: push
jobs:
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Github Issue
          body: Github Issue Body
          assignees: |
            anishp264
            anishpReviewer264
      - run: |
          echo ${{ steps.issue.outputs.issue }}
