name: CI
on:
  pull_request:
    branches: [develop, master]
  #push event triggered when a feature branch is merged with develop
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #cache node modules before running npm install
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          #path where the cache needs to be stored. Path depends on os and language: refer https://github.com/actions/cache
          path: ~/.npm
          #the key, to be generated if os changes and if package-lock.json file (dependencies) changes. the key name here is node
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          #restore key, incase if the cache cannot be found, the restore key could be used
          restore-keys: |
            #restore key starting with  ${{ runner.os }}-node-
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      # Install Dependencies
      - name: Install Dependencies
        run: npm install
      # Checking installed node versions
      - name: Check node versions
        run: node -v
      - name: Check npm version
        run: npm -v
      # Performing automated tests and code formatting
      - name: Perform Code format checks
        run: npm run format:check
      - name: Perform Automated tests
        run: npm test -- --coverage
        #need to set env to CI to prevent any terminals be shown while running test and coverage
        env:
          CI: true
      - name: Upload Test coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          #the coverage statement would be in a folder called coverage as in the project => build/coverage
          path: coverage
      # Build the project
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      - name: ZIP Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          # linux command, zipping the folders recursively, ie, gets all the folders and subfolders
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage
      - name: Create a Release
        #refer for workflow permissions: https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        #create a new release due to the usage of github plugin. Authenticate using a github token
        env:
          #GITHUB_TOKEN: ${{ github.token }}
          #using custom token instead of github token here to trigger the release workflow
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
      #The below action downloads the artifact
      #- uses: actions/download-artifact
      - name: Deploy to Staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: npx surge ./build https://mindless-street.surge.sh/ --token 780847c1fafc64fd211ead28b1ea00dc
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx surge ./build https://mindless-street.surge.sh/ --token 780847c1fafc64fd211ead28b1ea00dc
      #Uploading coverage reports
      - name: Upload coverage reports
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Open Issue
        if: failure() && github.event_name == 'pull_request'
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.CUSTOM_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
            "assignees": ["${{ github.event.pull_request.user.login }}"]
            }'
