name: CI
on:
  pull_request:
    branches: [develop]
  #push event triggered when a feature branch is merged with develop
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      # Install Dependencies
      - name: Install Dependencies
        run: npm install
      # Checking installed node versions
      - name: Check node versions
        run: node -v
      - name: Check npm version
        run: npm -v
      - name: check token
        run: ${{ secrets.SURGE_TOKEN }}
      # Performing automated tests and code formatting
      - name: Perform Code format checks
        run: npm run format:check
      - name: Perform Automated tests
        run: npm test -- --coverage
        #need to set env to CI to prevent any terminals be shown while running test and coverage
        env:
          CI: true
      # Build the project
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to Surge
        if: github.event_name == 'push'
        run: npx surge ./build https://mindless-street.surge.sh/ --token 1678041085579
